language: go
go_import_path: github.com/frankban/quicktest

arch:
  - amd64
  - ppc64le

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - 1.x
  - master

jobs:
 exclude:
  - arch: ppc64le
    go: master

script:
  - GO111MODULE=on go test -race ./...
  - GO111MODULE=on go test -v -race ./...
